#SpringSettings
server:
  port: 8091
  error:
    include-message: always

spring:
  #Liquibase
  liquibase:
    change-log: classpath:changelog/db.changelog-master.yml
    default-schema: public
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    clear-checksums: true
    enabled: true

  datasource:
    #HSQLDB
    #driver-class-name: org.hsqldb.jdbc.JDBCDriver
    #url: jdbc:hsqldb:mem:testdb;
    #username: TSuleymanov
    #password:

    #PostgreSQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  #Kafka
  kafka:
    bootstrap-servers: loclahost:29092
    consumer:
      group-id: producerServer
    producer:
      client-id: consumerServer

  wsdl:
    location: "wsdl/calcul.wsdl"